---
title: "Correlations"
author: "Ange Olson"
date: "`r Sys.Date()`"`
output: html_document
---

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```


```{r}
# read in dataset
airbnb <- read.csv("NYC ABS.csv", header = TRUE)
```

## Correlation Between Price (Y) and Availability (X)

```{r}
plot(x=airbnb$availability_365, y=airbnb$price)
cor.test(x=airbnb$availability_365, y=airbnb$price)
```

## Correlation Between Number of Reviews (Y) and Price (X) 

```{r}
plot(y=airbnb$number_of_reviews, x=airbnb$price)
cor.test(y=airbnb$number_of_reviews, x=airbnb$price)
```


```{r}

```












